langchain
langchain-core
langgraph
langchain-openai
python-dotenv
langchain-google-genai
langchain-community
chromadb
sentence-transformers
langchain-chroma
fastapi
uvicorn
python-multipart
langchain-experimental
langchain-huggingface
rank_bm25
langsmith